version: '3.8'
services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    hostname: mongo1
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo1:/data/db
    networks:
      - mongo-cluster-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo2:
    image: mongo:latest
    container_name: mongo2
    hostname: mongo2
    ports:
      - 27018:27017
    volumes:
      - ./data/mongo2:/data/db
    networks:
      - mongo-cluster-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo3:
    image: mongo:latest
    container_name: mongo3
    hostname: mongo3
    ports:
      - 27019:27017
    volumes:
      - ./data/mongo3:/data/db
    networks:
      - mongo-cluster-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-setup:
    image: mongo:latest
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-cluster-network
    entrypoint: >
      bash -c "
      sleep 10;
      echo 'Initializing replica set...';
      mongo --host mongo1:27017 <<EOF
      rs.initiate(
        {
          _id: 'rs0',
          members: [
            { _id: 0, host: 'mongo1:27017' },
            { _id: 1, host: 'mongo2:27017' },
            { _id: 2, host: 'mongo3:27017' }
          ]
        }
      )
      EOF
      "

networks:
  mongo-cluster-network:
    driver: bridge
