version: '3.8'

services:
  cassandra1:
    image: docker.io/bitnami/cassandra:5.0.2
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - 7000:7000
      - 9042:9042
    networks:
      cassandranetwork:
        ipv4_address: 172.24.0.2
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=nbd-casssandra-cluster
      - CASSANDRA_DATACENTER=dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra

  cassandra2:
    image: docker.io/bitnami/cassandra:5.0.2
    container_name: cassandra2
    hostname: cassandra2
    ports:
      - 7001:7000
      - 9043:9042
    networks:
      cassandranetwork:
        ipv4_address: 172.24.0.3
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=nbd-casssandra-cluster
      - CASSANDRA_DATACENTER=dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra

networks:
  cassandranetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16